"use client"
import { SignedIn, SignedOut, SignInButton, UserButton, useUser } from "@clerk/nextjs"
import { useState } from "react"

type Lang = "en" | "ru" | "zh" | "hi" | "es" | "pt"
type Answers = Record<string, string | string[]>

const LANG_LABELS: Record<Lang, string> = { en: "EN", ru: "RU", zh: "中文", hi: "हिं", es: "ES", pt: "PT" }
const LANGS: Lang[] = ["en", "ru", "zh", "hi", "es", "pt"]

const BLOCKS = [
  { id: "A", questions: [
    { key: "field", type: "single+other" },
    { key: "exp", type: "single" },
    { key: "degree", type: "single" },
    { key: "role", type: "single+other" },
  ]},
  { id: "B", questions: [
    { key: "awards", type: "multi+other" },
    { key: "membership", type: "single+other" },
    { key: "media", type: "multi+other" },
    { key: "judging", type: "multi+other" },
    { key: "contributions", type: "multi+other" },
    { key: "articles", type: "multi+other" },
    { key: "exhibitions", type: "single+other" },
    { key: "critical_role", type: "single+other" },
    { key: "salary", type: "single" },
    { key: "commercial", type: "single" },
  ]},
  { id: "C", questions: [
    { key: "niw_merit", type: "single+other" },
    { key: "niw_importance", type: "single" },
    { key: "niw_positioned", type: "multi+other" },
    { key: "niw_justification", type: "single+other" },
  ]},
  { id: "D", questions: [
    { key: "evidence", type: "multi" },
  ]},
]

const T: Record<Lang, Record<string, any>> = {
  en: {
    title: "Free EB1A / NIW Assessment",
    subtitle: "Answer questions about your professional profile. Get an AI-powered analysis of your US immigration pathway.",
    anonymous: "Anonymous · No personal data required · ~5 minutes",
    start: "Start Free Assessment",
    next: "Continue",
    back: "Back",
    analyze: "Analyze My Profile",
    analyzing: "AI is analyzing your profile...",
    other_label: "Other / add your own:",
    other_placeholder: "Describe in your own words...",
    result_title: "Your Assessment Result",
    eb1a: "EB1A — Extraordinary Ability",
    niw: "EB2-NIW — National Interest Waiver",
    strong: "Strong",
    moderate: "Moderate",
    weak: "Weak",
    strong_criteria: "Strong criteria",
    weak_criteria: "Needs development",
    recommendation: "Recommendation",
    next_steps: "Recommended Next Steps",
    timeline: "Timeline",
    alt_visas: "Alternative Visa Options",
    evidence_gaps: "Missing Evidence",
    cta_build: "Build Your Case — $499",
    cta_expert: "Expert Review — $149",
    cta_retake: "Retake Assessment",
    disclaimer: "⚠️ This assessment is generated by AI and is for informational purposes only. It does not constitute legal advice. Immigration law is complex and fact-specific — results may be inaccurate. Always consult a licensed US immigration attorney before making any decisions.",
    disclaimer_cta: "Get Attorney Review — $149",
    block_A: "Block A — Professional Profile",
    block_B: "Block B — EB-1A Criteria (10)",
    block_C: "Block C — National Interest Waiver (NIW)",
    block_D: "Block D — Evidence Availability",
    step: (s: number, total: number) => `Block ${s} of ${total}`,
    q: {
      field: { label: "Field of expertise", opts: ["Science / Research","Tech / Engineering","Business / Entrepreneurship","Medical / Healthcare","Arts / Creative","Law / Policy","Finance / Economics","Education"] },
      exp: { label: "Years of professional experience", opts: ["1–3 years","4–7 years","8–15 years","15+ years"] },
      degree: { label: "Highest academic degree", opts: ["Bachelor's","Master's","PhD / MD / JD","No degree"] },
      role: { label: "Current professional role", opts: ["Employee / Specialist","Manager / Team Lead","Director / VP","Founder / Co-Founder","Independent Expert / Consultant"] },
      awards: { label: "Professional awards recognized outside your employer?", sublabel: "Select all that apply", opts: ["International competitive award","National competitive award","Regional award","Internal / corporate only","None"] },
      membership: { label: "Membership in associations requiring outstanding achievement", opts: ["Yes — competitive / exclusive membership","Yes — open / basic membership","No","Not sure"] },
      media: { label: "Third-party media or publications featured you or your work?", sublabel: "Select all that apply", opts: ["National media","International media","Industry / niche media","Company press release only","None"] },
      judging: { label: "Invited to evaluate others' work?", sublabel: "Select all that apply", opts: ["Peer reviewer for journals","Competition judge","Grant / committee reviewer","Conference program committee","Not invited"] },
      contributions: { label: "Original contribution used or cited by others outside your organization?", sublabel: "Select all that apply", opts: ["Patents or industry standards","Technology adopted by other organizations","Methodology widely referenced","Open source with significant adoption","None"] },
      articles: { label: "Papers authored in professional publications?", sublabel: "Select all that apply", opts: ["Peer-reviewed journals (Scopus / WoS)","Conference proceedings","Industry publications","Books or book chapters","No publications"] },
      exhibitions: { label: "Artistic exhibitions (arts / creative only — others choose N/A)", opts: ["International exhibitions","National exhibitions","Local exhibitions","Not applicable"] },
      critical_role: { label: "Leading or critical role with measurable impact?", opts: ["Senior leadership (C-level, VP)","Director / Head of unit","Founder / key founding role","Critical technical / scientific role","No significant role"] },
      salary: { label: "Compensation relative to peers in your field and region", opts: ["Top 5% or higher","Top 10%","Above average","Average","Not sure"] },
      commercial: { label: "Commercial success or measurable market impact", sublabel: "Arts / performing arts only — others select N/A", opts: ["Significant (major revenue / adoption)","Moderate","Limited","Not applicable"] },
      niw_merit: { label: "Planned work or endeavor in the United States?", sublabel: "NIW requires work with direct US national impact — beyond your personal career", opts: ["Scientific research with US national impact","Technology / product with measurable US impact","Public health / healthcare improvement for the US","US infrastructure / energy / environment","US education / national workforce development","Business only (local market, no broader national impact)"] },
      niw_importance: { label: "At what level do you expect your work in the US to have impact (approximate)?", sublabel: "This is for initial strategy only and does not have to be perfectly defined at this stage.", opts: ["Nationwide (all US)","Multi-state / regional","One city or local market only","Hard to define"] },
      niw_positioned: { label: "Evidence you are well-positioned to execute this work in the US?", sublabel: "Select all that apply", opts: ["US-based partners or collaborators","LOI or contracts from US organizations","Funding or grants related to this work","Publications directly relevant to the US endeavor","Track record of success in this field","Nothing yet"] },
      niw_justification: { label: "Why should the US waive the normal job offer requirement?", sublabel: "The balance test — why is it in US national interest to waive PERM", opts: ["Urgent national need — delay would harm US interests","Unique expertise unavailable among US workers","Work benefits so significant that labor certification is impractical","Field where recruiting foreign nationals is standard (research, academia)"] },
      evidence: { label: "Evidence currently available?", sublabel: "Select all that apply", opts: ["CV / Resume","Award certificates or diplomas","Publication PDFs or links","Proof of judging / peer review invitations","Letters of recommendation from experts","Employment letters with role description","Media articles about you","Salary / compensation documents","Patent documents","None yet"] },
    },
  },
  ru: {
    title: "Бесплатная оценка EB1A / NIW",
    subtitle: "Ответьте на вопросы. Получите AI-анализ вашего иммиграционного пути в США.",
    anonymous: "Анонимно · Личные данные не требуются · ~5 минут",
    start: "Начать бесплатную оценку",
    next: "Продолжить",
    back: "Назад",
    analyze: "Проанализировать профиль",
    analyzing: "AI анализирует ваш профиль...",
    other_label: "Другое / свой вариант:",
    other_placeholder: "Опишите своими словами...",
    result_title: "Результат оценки",
    eb1a: "EB1A — Экстраординарные способности",
    niw: "EB2-NIW — Национальный интерес",
    strong: "Сильный",
    moderate: "Средний",
    weak: "Слабый",
    strong_criteria: "Сильные критерии",
    weak_criteria: "Требует развития",
    recommendation: "Рекомендация",
    next_steps: "Рекомендуемые следующие шаги",
    timeline: "Сроки",
    alt_visas: "Альтернативные визы",
    evidence_gaps: "Недостающие доказательства",
    cta_build: "Построить кейс — $499",
    cta_expert: "Проверка эксперта — $149",
    cta_retake: "Пройти заново",
    disclaimer: "⚠️ Эта оценка сгенерирована AI и носит исключительно информационный характер. Она не является юридической консультацией. Иммиграционное право сложное и зависит от конкретных фактов — результаты могут быть неточными. Всегда консультируйтесь с лицензированным американским иммиграционным адвокатом перед принятием решений.",
    disclaimer_cta: "Консультация адвоката — $149",
    block_A: "Блок A — Профессиональный профиль",
    block_B: "Блок B — Критерии EB-1A (10)",
    block_C: "Блок C — Национальный интерес (NIW)",
    block_D: "Блок D — Наличие доказательств",
    step: (s: number, total: number) => `Блок ${s} из ${total}`,
    q: {
      field: { label: "Область экспертизы", opts: ["Наука / Исследования","Технологии / Инжиниринг","Бизнес / Предпринимательство","Медицина / Здравоохранение","Искусство / Творчество","Право / Политика","Финансы / Экономика","Образование"] },
      exp: { label: "Лет профессионального опыта", opts: ["1–3 года","4–7 лет","8–15 лет","15+ лет"] },
      degree: { label: "Высшая академическая степень", opts: ["Бакалавр","Магистр","PhD / MD / JD","Нет степени"] },
      role: { label: "Текущая профессиональная роль", opts: ["Сотрудник / Специалист","Менеджер / Руководитель группы","Директор / VP","Основатель / Со-основатель","Независимый эксперт / Консультант"] },
      awards: { label: "Профессиональные награды за пределами работодателя?", sublabel: "Выберите все подходящие", opts: ["Международная конкурсная награда","Национальная конкурсная награда","Региональная награда","Только внутренняя / корпоративная","Нет"] },
      membership: { label: "Членство в ассоциациях, требующих выдающихся достижений", opts: ["Да — конкурсное / эксклюзивное","Да — открытое / базовое","Нет","Не уверен"] },
      media: { label: "Независимые СМИ публиковали о вас материалы?", sublabel: "Выберите все подходящие", opts: ["Национальные СМИ","Международные СМИ","Отраслевые / нишевые издания","Только корпоративный пресс-релиз","Нет"] },
      judging: { label: "Приглашали оценивать работы других?", sublabel: "Выберите все подходящие", opts: ["Рецензент журналов","Судья конкурсов","Рецензент грантов / комитетов","Член программного комитета конференции","Не приглашали"] },
      contributions: { label: "Оригинальный вклад используется другими за пределами вашей организации?", sublabel: "Выберите все подходящие", opts: ["Патенты или отраслевые стандарты","Технология принята другими организациями","Методология широко цитируется","Open source со значительным adoption","Нет"] },
      articles: { label: "Публикации в профессиональных изданиях?", sublabel: "Выберите все подходящие", opts: ["Рецензируемые журналы (Scopus / WoS)","Труды конференций","Отраслевые издания","Книги или главы книг","Публикаций нет"] },
      exhibitions: { label: "Художественные выставки (только искусство / творчество — остальные N/A)", opts: ["Международные выставки","Национальные выставки","Местные выставки","Не применимо"] },
      critical_role: { label: "Руководящая или критическая роль с измеримым влиянием?", opts: ["Высшее руководство (C-level, VP)","Директор / Руководитель подразделения","Основатель / ключевая учредительная роль","Критическая техническая / научная роль","Значимой роли не было"] },
      salary: { label: "Вознаграждение относительно коллег в вашей области и регионе", opts: ["Топ 5% и выше","Топ 10%","Выше среднего","Среднее","Не уверен"] },
      commercial: { label: "Коммерческий успех или измеримое влияние на рынок", sublabel: "Только для исполнительских искусств — остальные выбирают Н/А", opts: ["Значительный","Умеренный","Ограниченный","Не применимо"] },
      niw_merit: { label: "Планируемая работа или деятельность в США?", sublabel: "NIW требует прямого национального влияния на США — за рамками личной карьеры", opts: ["Научные исследования с национальным влиянием на США","Технологии / продукт с измеримым влиянием на США","Улучшение здравоохранения для США","Инфраструктура / энергетика / экология США","Образование / развитие национальных кадров США","Только бизнес (локальный рынок, без национального влияния)"] },
      niw_importance: { label: "На каком уровне вы ожидаете влияние вашей работы в США (приблизительно)?", sublabel: "Это только для первоначальной стратегии — не нужно определять точно на этом этапе.", opts: ["Вся страна (все США)","Несколько штатов / регион","Только один город или местный рынок","Сложно определить"] },
      niw_positioned: { label: "Доказательства готовности выполнять эту работу в США?", sublabel: "Выберите все подходящие", opts: ["Партнёры или коллаборации в США","LOI или контракты от американских организаций","Финансирование или гранты по этой теме","Публикации по теме деятельности в США","Подтверждённый опыт успеха в этой области","Пока ничего"] },
      niw_justification: { label: "Почему США должны освободить вас от требования о предложении работы?", sublabel: "Балансовый тест — почему в интересах США отказаться от PERM", opts: ["Срочная национальная потребность","Уникальная экспертиза, недоступная среди американских работников","Польза настолько значительна, что трудовая сертификация нецелесообразна","Область, где привлечение иностранных специалистов является стандартом"] },
      evidence: { label: "Какие доказательства есть в наличии?", sublabel: "Выберите все подходящие", opts: ["CV / Резюме","Сертификаты или дипломы о наградах","PDF публикаций или ссылки","Подтверждения рецензирования / приглашения в жюри","Рекомендательные письма от экспертов","Письма от работодателей с описанием роли","Медиа-статьи о вас","Документы о зарплате / вознаграждении","Патентные документы","Пока ничего"] },
    },
  },
  zh: {
    title: "免费 EB1A / NIW 评估", subtitle: "回答问题，获得AI驱动的美国移民途径分析。", anonymous: "匿名 · 无需个人数据 · 约5分钟", start: "开始免费评估", next: "继续", back: "返回", analyze: "分析我的档案", analyzing: "AI正在分析您的档案...", other_label: "其他：", other_placeholder: "用您自己的话描述...", result_title: "评估结果", eb1a: "EB1A — 杰出能力", niw: "EB2-NIW — 国家利益豁免", strong: "强", moderate: "中等", weak: "弱", strong_criteria: "强项", weak_criteria: "需要发展", recommendation: "建议", next_steps: "建议的后续步骤", timeline: "时间表", alt_visas: "替代签证选项", evidence_gaps: "缺少的证据", cta_build: "建立案例 — $499", cta_expert: "专家审核 — $149", cta_retake: "重新评估",
    disclaimer: "⚠️ 此评估由AI生成，仅供参考。不构成法律建议。移民法律复杂且因情况而异——结果可能不准确。在做出任何决定之前，请务必咨询持牌美国移民律师。",
    disclaimer_cta: "律师审核 — $149",
    block_A: "A — 职业档案", block_B: "B — EB-1A标准", block_C: "C — NIW", block_D: "D — 证据", step: (s: number, t: number) => `第${s}块/共${t}块`,
    q: {
      field: { label: "专业领域", opts: ["科学/研究","技术/工程","商业/创业","医学/医疗","艺术/创意","法律/政策","金融/经济","教育"] },
      exp: { label: "职业经验年数", opts: ["1–3年","4–7年","8–15年","15年以上"] },
      degree: { label: "最高学历", opts: ["学士","硕士","博士/医学博士/法学博士","无学位"] },
      role: { label: "当前职业角色", opts: ["员工/专家","经理/团队负责人","总监/VP","创始人/联合创始人","独立专家/顾问"] },
      awards: { label: "您是否获得过专业奖项？", sublabel: "选择所有适用项", opts: ["国际竞争性奖项","国家竞争性奖项","地区奖项","仅内部/企业奖项","无"] },
      membership: { label: "需要杰出成就的协会会员资格", opts: ["是——竞争性/独家","是——开放/基本","否","不确定"] },
      media: { label: "第三方媒体是否报道过您？", sublabel: "选择所有适用项", opts: ["国家媒体","国际媒体","行业媒体","仅公司新闻稿","无"] },
      judging: { label: "您是否被邀请评估他人的工作？", sublabel: "选择所有适用项", opts: ["期刊同行评审员","竞赛评委","基金/委员会评审员","会议程序委员会","未被邀请"] },
      contributions: { label: "您是否做出了被他人使用的原创贡献？", sublabel: "选择所有适用项", opts: ["专利或行业标准","被其他组织采用的技术","被广泛引用的方法论","重大开源项目","无"] },
      articles: { label: "您是否在专业出版物上发表过文章？", sublabel: "选择所有适用项", opts: ["同行评审期刊","会议论文集","行业出版物","书籍","无出版物"] },
      exhibitions: { label: "艺术展览（仅艺术/创意）", opts: ["国际展览","国家展览","地方展览","不适用"] },
      critical_role: { label: "您是否担任过具有影响的领导角色？", opts: ["高级领导(C级、VP)","总监/部门负责人","创始人","关键技术角色","无重要角色"] },
      salary: { label: "您的薪酬与同行相比", opts: ["前5%或更高","前10%","高于平均","平均","不确定"] },
      commercial: { label: "商业成功或可衡量的市场影响", sublabel: "仅适用于表演艺术——其他人选择不适用", opts: ["显著","适中","有限","不适用"] },
      niw_merit: { label: "您在美国计划的工作是什么？", sublabel: "NIW需要对美国有直接国家影响", opts: ["对美国有国家影响的科学研究","对美国有影响的技术/产品","改善美国公共卫生","美国基础设施/能源","美国教育/劳动力发展","仅本地商业"] },
      niw_importance: { label: "您预计在美国的工作将在什么层面产生影响（大致）？", sublabel: "这仅用于初步策略，此阶段无需精确定义。", opts: ["全国（全美）","多州/地区","仅本地","难以定义"] },
      niw_positioned: { label: "您是否有在美国执行工作的证据？", sublabel: "选择所有适用项", opts: ["美国合作伙伴","LOI或合同","相关资金/赠款","相关出版物","成功记录","暂无"] },
      niw_justification: { label: "为什么美国应该豁免工作邀请要求？", sublabel: "平衡测试", opts: ["紧迫的国家需求","独特专业知识","工作价值极大","招募外国人是标准做法"] },
      evidence: { label: "您目前有哪些证据？", sublabel: "选择所有适用项", opts: ["简历","奖项证书","出版物PDF","评审邀请","推荐信","就业信","媒体文章","薪资文件","专利文件","暂无"] },
    },
  },
  hi: {
    title: "निःशुल्क EB1A / NIW मूल्यांकन", subtitle: "प्रश्नों का उत्तर दें। AI-संचालित विश्लेषण पाएं।", anonymous: "गुमनाम · ~5 मिनट", start: "मूल्यांकन शुरू करें", next: "जारी रखें", back: "वापस", analyze: "विश्लेषण करें", analyzing: "AI विश्लेषण कर रहा है...", other_label: "अन्य:", other_placeholder: "अपने शब्दों में...", result_title: "परिणाम", eb1a: "EB1A — असाधारण क्षमता", niw: "EB2-NIW — राष्ट्रीय हित", strong: "मजबूत", moderate: "मध्यम", weak: "कमजोर", strong_criteria: "मजबूत", weak_criteria: "विकास चाहिए", recommendation: "सिफारिश", next_steps: "अगले कदम", timeline: "समयरेखा", alt_visas: "वैकल्पिक वीजा", evidence_gaps: "गायब साक्ष्य", cta_build: "केस बनाएं — $499", cta_expert: "विशेषज्ञ — $149", cta_retake: "फिर से",
    disclaimer: "⚠️ यह मूल्यांकन AI द्वारा उत्पन्न किया गया है और केवल सूचनात्मक उद्देश्यों के लिए है। यह कानूनी सलाह नहीं है। कोई भी निर्णय लेने से पहले हमेशा एक लाइसेंस प्राप्त अमेरिकी आप्रवासन वकील से परामर्श करें।",
    disclaimer_cta: "वकील समीक्षा — $149",
    block_A: "A — प्रोफ़ाइल", block_B: "B — EB-1A", block_C: "C — NIW", block_D: "D — साक्ष्य", step: (s: number, t: number) => `${s}/${t}`,
    q: {
      field: { label: "क्षेत्र", opts: ["विज्ञान","तकनीक","व्यापार","चिकित्सा","कला","कानून","वित्त","शिक्षा"] },
      exp: { label: "अनुभव के वर्ष", opts: ["1–3","4–7","8–15","15+"] },
      degree: { label: "डिग्री", opts: ["स्नातक","मास्टर्स","PhD/MD/JD","कोई नहीं"] },
      role: { label: "भूमिका", opts: ["कर्मचारी","प्रबंधक","निदेशक","संस्थापक","स्वतंत्र विशेषज्ञ"] },
      awards: { label: "पुरस्कार?", sublabel: "सभी चुनें", opts: ["अंतर्राष्ट्रीय","राष्ट्रीय","क्षेत्रीय","केवल आंतरिक","कोई नहीं"] },
      membership: { label: "प्रतिष्ठित संगठनों में सदस्यता?", opts: ["हां — प्रतिस्पर्धी","हां — खुली","नहीं","निश्चित नहीं"] },
      media: { label: "मीडिया कवरेज?", sublabel: "सभी चुनें", opts: ["राष्ट्रीय","अंतर्राष्ट्रीय","उद्योग","प्रेस विज्ञप्ति","कोई नहीं"] },
      judging: { label: "दूसरों के काम का मूल्यांकन?", sublabel: "सभी चुनें", opts: ["जर्नल समीक्षक","प्रतियोगिता न्यायाधीश","अनुदान समीक्षक","सम्मेलन","नहीं"] },
      contributions: { label: "मूल योगदान?", sublabel: "सभी चुनें", opts: ["पेटेंट","अपनाई तकनीक","संदर्भित पद्धति","ओपन सोर्स","कोई नहीं"] },
      articles: { label: "प्रकाशन?", sublabel: "सभी चुनें", opts: ["पीयर-समीक्षित","सम्मेलन","उद्योग","पुस्तकें","कोई नहीं"] },
      exhibitions: { label: "कलात्मक प्रदर्शनियां", opts: ["अंतर्राष्ट्रीय","राष्ट्रीय","स्थानीय","लागू नहीं"] },
      critical_role: { label: "नेतृत्व भूमिका?", opts: ["C-level/VP","निदेशक","संस्थापक","तकनीकी","कोई नहीं"] },
      salary: { label: "वेतन तुलना", opts: ["शीर्ष 5%","शीर्ष 10%","औसत से ऊपर","औसत","निश्चित नहीं"] },
      commercial: { label: "व्यावसायिक सफलता या बाजार प्रभाव", sublabel: "केवल प्रदर्शन कलाओं के लिए — अन्य N/A चुनें", opts: ["महत्वपूर्ण","मध्यम","सीमित","लागू नहीं"] },
      niw_merit: { label: "अमेरिका में आपकी योजना?", sublabel: "अमेरिका पर प्रत्यक्ष राष्ट्रीय प्रभाव", opts: ["अमेरिकी वैज्ञानिक अनुसंधान","अमेरिकी तकनीक/उत्पाद","अमेरिकी स्वास्थ्य सेवा","अमेरिकी बुनियादी ढांचा","अमेरिकी शिक्षा","केवल स्थानीय व्यापार"] },
      niw_importance: { label: "आप अमेरिका में अपने काम का किस स्तर पर प्रभाव अपेक्षित करते हैं?", sublabel: "यह केवल प्रारंभिक रणनीति के लिए है — इस चरण में सटीक होना जरूरी नहीं।", opts: ["राष्ट्रव्यापी (पूरे अमेरिका)","बहु-राज्य / क्षेत्रीय","केवल एक शहर या स्थानीय बाजार","परिभाषित करना कठिन"] },
      niw_positioned: { label: "अमेरिका में कार्य करने की क्षमता का प्रमाण?", sublabel: "सभी चुनें", opts: ["अमेरिकी भागीदार","LOI/अनुबंध","फंडिंग","प्रकाशन","सफलता का रिकॉर्ड","कुछ नहीं"] },
      niw_justification: { label: "PERM छूट क्यों?", sublabel: "संतुलन परीक्षण", opts: ["राष्ट्रीय आवश्यकता","अद्वितीय कौशल","बहुत महत्वपूर्ण काम","मानक भर्ती प्रथा"] },
      evidence: { label: "उपलब्ध साक्ष्य?", sublabel: "सभी चुनें", opts: ["CV","पुरस्कार प्रमाण","प्रकाशन","समीक्षा आमंत्रण","सिफारिश पत्र","रोजगार पत्र","मीडिया","वेतन दस्तावेज","पेटेंट","कुछ नहीं"] },
    },
  },
  es: {
    title: "Evaluación Gratuita EB1A / NIW", subtitle: "Responda preguntas. Obtenga análisis con IA.", anonymous: "Anónimo · ~5 minutos", start: "Iniciar Evaluación", next: "Continuar", back: "Atrás", analyze: "Analizar Mi Perfil", analyzing: "IA analizando su perfil...", other_label: "Otro:", other_placeholder: "Describa...", result_title: "Resultado", eb1a: "EB1A — Habilidad Extraordinaria", niw: "EB2-NIW — Interés Nacional", strong: "Fuerte", moderate: "Moderado", weak: "Débil", strong_criteria: "Criterios fuertes", weak_criteria: "Necesita desarrollo", recommendation: "Recomendación", next_steps: "Próximos pasos", timeline: "Cronograma", alt_visas: "Visas alternativas", evidence_gaps: "Evidencia faltante", cta_build: "Construir Caso — $499", cta_expert: "Experto — $149", cta_retake: "Repetir",
    disclaimer: "⚠️ Esta evaluación es generada por IA y es solo informativa. No constituye asesoramiento legal. La ley de inmigración es compleja — los resultados pueden ser inexactos. Siempre consulte a un abogado de inmigración de EE.UU. antes de tomar decisiones.",
    disclaimer_cta: "Revisión de abogado — $149",
    block_A: "A — Perfil", block_B: "B — Criterios EB-1A", block_C: "C — NIW", block_D: "D — Evidencia", step: (s: number, t: number) => `Bloque ${s} de ${t}`,
    q: {
      field: { label: "Campo", opts: ["Ciencia","Tecnología","Negocios","Medicina","Arte","Derecho","Finanzas","Educación"] },
      exp: { label: "Años de experiencia", opts: ["1–3","4–7","8–15","15+"] },
      degree: { label: "Grado académico", opts: ["Licenciatura","Maestría","PhD/MD/JD","Sin título"] },
      role: { label: "Rol actual", opts: ["Empleado","Gerente","Director/VP","Fundador","Consultor"] },
      awards: { label: "¿Premios reconocidos fuera de su empleador?", sublabel: "Todo lo que aplique", opts: ["Internacional","Nacional","Regional","Solo interno","Ninguno"] },
      membership: { label: "¿Membresía que requiere logros?", opts: ["Sí — competitiva","Sí — abierta","No","No estoy seguro"] },
      media: { label: "¿Medios de terceros lo han destacado?", sublabel: "Todo lo que aplique", opts: ["Nacional","Internacional","Industria","Solo corporativo","Ninguno"] },
      judging: { label: "¿Invitado a evaluar trabajo de otros?", sublabel: "Todo lo que aplique", opts: ["Revisor revistas","Juez competencias","Revisor becas","Comité conferencia","No"] },
      contributions: { label: "¿Contribución original usada por otros?", sublabel: "Todo lo que aplique", opts: ["Patentes/estándares","Tecnología adoptada","Metodología citada","Código abierto","Ninguno"] },
      articles: { label: "¿Artículos en publicaciones profesionales?", sublabel: "Todo lo que aplique", opts: ["Revistas revisadas","Conferencias","Industria","Libros","Sin publicaciones"] },
      exhibitions: { label: "Exposiciones artísticas (solo arte)", opts: ["Internacional","Nacional","Local","No aplica"] },
      critical_role: { label: "¿Rol de liderazgo con impacto?", opts: ["C-level/VP","Director","Fundador","Técnico crítico","Sin rol"] },
      salary: { label: "Compensación vs. pares", opts: ["Top 5%","Top 10%","Por encima","Promedio","No sé"] },
      commercial: { label: "Éxito comercial o impacto de mercado medible", sublabel: "Solo para artes escénicas — los demás seleccionen N/A", opts: ["Significativo","Moderado","Limitado","No aplica"] },
      niw_merit: { label: "¿Su trabajo planificado en EE.UU.?", sublabel: "NIW requiere impacto nacional directo", opts: ["Investigación científica","Tecnología con impacto","Salud pública","Infraestructura","Educación","Solo negocio local"] },
      niw_importance: { label: "¿En qué nivel espera que su trabajo en EE.UU. tenga impacto (aproximado)?", sublabel: "Esto es solo para estrategia inicial — no es necesario definirlo con precisión en esta etapa.", opts: ["Nacional (todo EE.UU.)","Multi-estado / regional","Solo una ciudad o mercado local","Difícil de definir"] },
      niw_positioned: { label: "¿Evidencia de estar posicionado en EE.UU.?", sublabel: "Todo lo que aplique", opts: ["Socios EE.UU.","LOI/contratos","Financiación","Publicaciones","Historial","Nada"] },
      niw_justification: { label: "¿Por qué eximir oferta de trabajo?", sublabel: "Prueba de equilibrio", opts: ["Necesidad urgente","Experiencia única","Beneficios enormes","Campo estándar"] },
      evidence: { label: "¿Qué evidencia tiene?", sublabel: "Todo lo que aplique", opts: ["CV","Certificados","Publicaciones","Prueba revisión","Recomendaciones","Cartas empleo","Medios","Salario","Patentes","Nada"] },
    },
  },
  pt: {
    title: "Avaliação Gratuita EB1A / NIW", subtitle: "Responda perguntas. Obtenha análise com IA.", anonymous: "Anônimo · ~5 minutos", start: "Iniciar Avaliação", next: "Continuar", back: "Voltar", analyze: "Analisar Perfil", analyzing: "IA analisando seu perfil...", other_label: "Outro:", other_placeholder: "Descreva...", result_title: "Resultado", eb1a: "EB1A — Habilidade Extraordinária", niw: "EB2-NIW — Interesse Nacional", strong: "Forte", moderate: "Moderado", weak: "Fraco", strong_criteria: "Critérios fortes", weak_criteria: "Precisa desenvolvimento", recommendation: "Recomendação", next_steps: "Próximos passos", timeline: "Cronograma", alt_visas: "Vistos alternativos", evidence_gaps: "Evidências em falta", cta_build: "Construir Caso — $499", cta_expert: "Especialista — $149", cta_retake: "Refazer",
    disclaimer: "⚠️ Esta avaliação é gerada por IA e é apenas informativa. Não constitui aconselhamento jurídico. A lei de imigração é complexa — os resultados podem ser imprecisos. Consulte sempre um advogado de imigração dos EUA antes de tomar decisões.",
    disclaimer_cta: "Revisão de advogado — $149",
    block_A: "A — Perfil", block_B: "B — Critérios EB-1A", block_C: "C — NIW", block_D: "D — Evidências", step: (s: number, t: number) => `Bloco ${s} de ${t}`,
    q: {
      field: { label: "Área", opts: ["Ciência","Tecnologia","Negócios","Medicina","Arte","Direito","Finanças","Educação"] },
      exp: { label: "Anos de experiência", opts: ["1–3","4–7","8–15","15+"] },
      degree: { label: "Grau acadêmico", opts: ["Bacharelado","Mestrado","PhD/MD/JD","Sem diploma"] },
      role: { label: "Função atual", opts: ["Funcionário","Gerente","Diretor/VP","Fundador","Consultor"] },
      awards: { label: "Prêmios reconhecidos fora do empregador?", sublabel: "Tudo que se aplica", opts: ["Internacional","Nacional","Regional","Apenas interno","Nenhum"] },
      membership: { label: "Filiação que exige conquistas?", opts: ["Sim — competitiva","Sim — aberta","Não","Não tenho certeza"] },
      media: { label: "Mídia de terceiros destacou você?", sublabel: "Tudo que se aplica", opts: ["Nacional","Internacional","Setor","Apenas corporativo","Nenhum"] },
      judging: { label: "Convidado para avaliar outros?", sublabel: "Tudo que se aplica", opts: ["Revisor periódicos","Juiz competições","Revisor bolsas","Comitê conferência","Não"] },
      contributions: { label: "Contribuição original usada por outros?", sublabel: "Tudo que se aplica", opts: ["Patentes/padrões","Tecnologia adotada","Metodologia citada","Código aberto","Nenhum"] },
      articles: { label: "Artigos em publicações profissionais?", sublabel: "Tudo que se aplica", opts: ["Periódicos revisados","Conferências","Setor","Livros","Sem publicações"] },
      exhibitions: { label: "Exposições artísticas (apenas arte)", opts: ["Internacional","Nacional","Local","Não aplicável"] },
      critical_role: { label: "Papel de liderança com impacto?", opts: ["C-level/VP","Diretor","Fundador","Técnico crítico","Sem papel"] },
      salary: { label: "Remuneração vs. pares", opts: ["Top 5%","Top 10%","Acima da média","Média","Não sei"] },
      commercial: { label: "Sucesso comercial ou impacto de mercado mensurável", sublabel: "Apenas para artes cênicas — os demais selecionem N/A", opts: ["Significativo","Moderado","Limitado","Não aplicável"] },
      niw_merit: { label: "Seu trabalho planejado nos EUA?", sublabel: "NIW requer impacto nacional direto", opts: ["Pesquisa científica","Tecnologia com impacto","Saúde pública","Infraestrutura","Educação","Apenas negócio local"] },
      niw_importance: { label: "Em que nível você espera que seu trabalho nos EUA tenha impacto (aproximado)?", sublabel: "Isso é apenas para estratégia inicial — não precisa ser definido com precisão nesta etapa.", opts: ["Nacional (todo os EUA)","Multi-estado / regional","Apenas uma cidade ou mercado local","Difícil de definir"] },
      niw_positioned: { label: "Evidência de estar posicionado nos EUA?", sublabel: "Tudo que se aplica", opts: ["Parceiros EUA","LOI/contratos","Financiamento","Publicações","Histórico","Nada"] },
      niw_justification: { label: "Por que dispensar oferta de emprego?", sublabel: "Teste de equilíbrio", opts: ["Necessidade urgente","Expertise única","Benefícios enormes","Campo padrão"] },
      evidence: { label: "Que evidências você tem?", sublabel: "Tudo que se aplica", opts: ["CV","Certificados","Publicações","Prova revisão","Recomendações","Cartas empleo","Mídia","Salário","Patentes","Nada"] },
    },
  },
}

export default function AssessmentPage() {
  const [lang, setLang] = useState<Lang>("en")
  const [blockIdx, setBlockIdx] = useState(-1)
  const [answers, setAnswers] = useState<Answers>({})
  const [other, setOther] = useState<Record<string, string>>({})
  const [aiResult, setAiResult] = useState<any>(null)
  const [aiError, setAiError] = useState(false)
const [chatOpen, setChatOpen] = useState(false)
const [chatName, setChatName] = useState("")
const [chatEmail, setChatEmail] = useState("")
const [chatMsg, setChatMsg] = useState("")
const [chatSent, setChatSent] = useState(false)
const [chatLoading, setChatLoading] = useState(false)
  const [cvFile, setCvFile] = useState<File | null>(null)
const [cvParsing, setCvParsing] = useState(false)
const [cvParsed, setCvParsed] = useState(false)
  const [cvText, setCvText] = useState("")
  const { user } = useUser()
  const t = T[lang]
  const curBlock = BLOCKS[blockIdx]

  const setSingle = (key: string, val: string) => setAnswers(p => ({ ...p, [key]: val }))
  const toggleMulti = (key: string, idx: string) => {
    const cur = (answers[key] as string[]) || []
    setAnswers(p => ({ ...p, [key]: cur.includes(idx) ? cur.filter(v => v !== idx) : [...cur, idx] }))
  }
  const isSel = (key: string, idx: string) => {
    const v = answers[key]
    return Array.isArray(v) ? v.includes(idx) : v === idx
  }
  const blockOk = () => {
    if (!curBlock) return false
    return curBlock.questions.every(({ key, type }) => {
      if (type.includes("multi")) return ((answers[key] as string[]) || []).length > 0 || !!other[key]
      return !!answers[key] || !!other[key]
    })
  }

  // Build human-readable answers for AI
  const buildReadableAnswers = () => {
    const readable: Record<string, any> = {}
    Object.keys(answers).forEach(key => {
      const q = t.q[key]
      if (!q) return
      const val = answers[key]
      if (Array.isArray(val)) {
        readable[key] = val.map((idx: string) => q.opts[parseInt(idx)] || idx).join(", ")
      } else {
        readable[key] = q.opts[parseInt(val as string)] || val
      }
      if (other[key]) readable[`${key}_text`] = other[key]
    })
    return readable
  }

  const goNext = async () => {
    window.scrollTo(0, 0)
    if (blockIdx === BLOCKS.length - 1) {
      setBlockIdx(BLOCKS.length) // loading
      try {
        const readableAnswers = buildReadableAnswers()
        const res = await fetch("/api/assess", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ answers: readableAnswers, lang, cvText, userId: user?.id })
        })
        if (!res.ok) throw new Error("API error")
        const data = await res.json()
        setAiResult(data)
      } catch (e) {
        setAiError(true)
      }
      setBlockIdx(BLOCKS.length + 1)
    } else {
      setBlockIdx(i => i + 1)
    }
  }

  const renderQ = (key: string, type: string) => {
    const q = t.q[key]; if (!q) return null
    const multi = type.includes("multi")
    const hasOth = type.includes("other")
    return (
      <div key={key} className="mb-8">
        <p className="text-sm font-bold text-slate-800 mb-1">{q.label}</p>
        {q.sublabel && <p className="text-xs text-slate-500 mb-3">{q.sublabel}</p>}
        <div className={multi ? "flex flex-wrap gap-2" : "grid gap-2"}>
          {q.opts.map((opt: string, i: number) => {
            const idx = String(i), sel = isSel(key, idx)
            return (
              <button key={i} onClick={() => multi ? toggleMulti(key, idx) : setSingle(key, idx)}
                className={`${multi ? "px-3 py-2" : "w-full text-left px-4 py-3"} rounded-xl border text-sm font-medium transition-all ${sel ? "bg-blue-600 text-white border-blue-600 shadow-md" : "bg-white text-slate-700 border-slate-200 hover:border-blue-400 hover:bg-blue-50"}`}>
                {opt}
              </button>
            )
          })}
        </div>
        {hasOth && (
          <div className="mt-3">
            <p className="text-xs text-slate-400 mb-1">{t.other_label}</p>
            <textarea value={other[key] || ""} onChange={e => setOther(p => ({ ...p, [key]: e.target.value }))}
              placeholder={t.other_placeholder} rows={2}
              className="w-full text-sm border border-slate-200 rounded-xl px-3 py-2 resize-none focus:outline-none focus:border-blue-400 text-slate-700 placeholder-slate-300" />
          </div>
        )}
      </div>
    )
  }

  const handleCheckout = async (product: string) => {
  const res = await fetch("/api/checkout", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ product }),
  })
  const data = await res.json()
  if (data.url) window.location.href = data.url
}
  const sendChat = async () => {
  if (!chatName || !chatEmail || !chatMsg) return
  setChatLoading(true)
  try {
    await fetch("/api/contact", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: chatName, email: chatEmail, message: chatMsg, lang })
    })
    setChatSent(true)
  } catch (e) {}
  setChatLoading(false)
}
  const handleCvUpload = async (file: File) => {
  setCvFile(file)
    setTimeout(() => window.scrollTo({ top: 0, behavior: "smooth" }), 100)
  setCvParsing(true)
  try {
    const formData = new FormData()
    formData.append("cv", file)
    formData.append("lang", lang)
    const res = await fetch("/api/parse-cv", { method: "POST", body: formData })
    if (res.ok) {
      const data = await res.json()
      const newAnswers: Answers = {}
      if (data.field !== null) newAnswers.field = String(data.field)
      if (data.exp !== null) newAnswers.exp = String(data.exp)
      if (data.degree !== null) newAnswers.degree = String(data.degree)
      if (data.role !== null) newAnswers.role = String(data.role)
      if (data.awards) newAnswers.awards = data.awards.map(String)
      if (data.membership !== null) newAnswers.membership = String(data.membership)
      if (data.media) newAnswers.media = data.media.map(String)
      if (data.judging) newAnswers.judging = data.judging.map(String)
      if (data.contributions) newAnswers.contributions = data.contributions.map(String)
      if (data.articles) newAnswers.articles = data.articles.map(String)
      if (data.critical_role !== null) newAnswers.critical_role = String(data.critical_role)
      if (data.salary !== null) newAnswers.salary = String(data.salary)
      setAnswers(newAnswers)
      if (data.role_text) setOther(p => ({ ...p, role: data.role_text }))
      if (data.field_text) setOther(p => ({ ...p, field: data.field_text }))
      setCvParsed(true)
      if (data.summary) setCvText(data.summary)
    }
  } catch (e) {}
  setCvParsing(false)
}
  const renderResult = () => {
    const r = aiResult
    const lc = (l: string) => l === "strong" ? "text-emerald-700 bg-emerald-50 border-emerald-200" : l === "moderate" ? "text-amber-700 bg-amber-50 border-amber-200" : "text-red-600 bg-red-50 border-red-200"
    const lt = (l: string) => l === "strong" ? t.strong : l === "moderate" ? t.moderate : t.weak

    return (
      <div className="max-w-2xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-bold text-slate-900 mb-6 text-center">{t.result_title}</h1>

        {/* Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mb-6">
          <p className="text-xs text-amber-800 leading-relaxed">{t.disclaimer}</p>
        </div>

        {aiError && (
          <div className="bg-red-50 border border-red-200 rounded-2xl p-4 mb-6">
            <p className="text-sm text-red-700">AI analysis temporarily unavailable. Please try again or contact us for a manual review.</p>
          </div>
        )}

        {r && (
          <>
            {/* Scores */}
            <div className="grid gap-3 mb-6">
              {[{ label: "EB1A", name: t.eb1a, level: r.eb1a_level }, { label: "NIW", name: t.niw, level: r.niw_level }].map(item => (
                <div key={item.label} className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
                  <div className="flex items-center justify-between mb-2">
                    <div><p className="text-xs text-slate-400 uppercase tracking-wide mb-0.5">{item.label}</p><p className="font-semibold text-slate-800 text-sm">{item.name}</p></div>
                    <span className={`text-sm font-bold px-4 py-1.5 rounded-full border ${lc(item.level)}`}>{lt(item.level)}</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">{item.label === "EB1A" ? r.eb1a_score_explanation : r.niw_score_explanation}</p>
                </div>
              ))}
            </div>

            {/* Criteria */}
            <div className="bg-white rounded-2xl border border-slate-200 p-5 mb-5 shadow-sm">
              <p className="text-xs font-bold text-emerald-700 uppercase tracking-wide mb-2">{t.strong_criteria}</p>
              <div className="flex flex-wrap gap-2 mb-4">
                {r.strong_criteria?.length > 0 ? r.strong_criteria.map((c: string) => <span key={c} className="bg-emerald-100 text-emerald-800 text-xs font-semibold px-3 py-1 rounded-full">{c}</span>) : <span className="text-slate-400 text-xs">—</span>}
              </div>
              <p className="text-xs font-bold text-red-600 uppercase tracking-wide mb-2">{t.weak_criteria}</p>
              <div className="flex flex-wrap gap-2">
                {r.weak_criteria?.map((c: string) => <span key={c} className="bg-red-100 text-red-700 text-xs font-semibold px-3 py-1 rounded-full">{c}</span>)}
              </div>
            </div>

            {/* Recommendation */}
            <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5 mb-5">
              <p className="text-xs font-bold text-blue-700 uppercase tracking-wide mb-2">{t.recommendation}</p>
              <p className="text-slate-700 text-sm leading-relaxed">{r.detailed_recommendation}</p>
            </div>

            {/* Next steps */}
            {r.next_steps?.length > 0 && (
              <div className="bg-white rounded-2xl border border-slate-200 p-5 mb-5 shadow-sm">
                <p className="text-xs font-bold text-slate-700 uppercase tracking-wide mb-3">{t.next_steps}</p>
                <ol className="space-y-2">
                  {r.next_steps.map((step: string, i: number) => (
                    <li key={i} className="flex gap-3 text-sm text-slate-700">
                      <span className="w-5 h-5 rounded-full bg-blue-100 text-blue-700 text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">{i + 1}</span>
                      {step}
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {/* Timeline */}
            {r.timeline && (
              <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 mb-5">
                <p className="text-xs font-bold text-slate-600 uppercase tracking-wide mb-1">{t.timeline}</p>
                <p className="text-sm text-slate-700">{r.timeline}</p>
              </div>
            )}

            {/* Alternative visas */}
            {r.alternative_visas?.length > 0 && (
              <div className="bg-white rounded-2xl border border-slate-200 p-5 mb-5 shadow-sm">
                <p className="text-xs font-bold text-slate-700 uppercase tracking-wide mb-2">{t.alt_visas}</p>
                <div className="flex flex-wrap gap-2">
                  {r.alternative_visas.map((v: string) => <span key={v} className="bg-slate-100 text-slate-700 text-xs font-semibold px-3 py-1 rounded-full">{v}</span>)}
                </div>
              </div>
            )}

            {/* Evidence gaps */}
            {r.evidence_gaps?.length > 0 && (
              <div className="bg-orange-50 border border-orange-200 rounded-2xl p-5 mb-6">
                <p className="text-xs font-bold text-orange-700 uppercase tracking-wide mb-2">{t.evidence_gaps}</p>
                <ul className="space-y-1">
                  {r.evidence_gaps.map((g: string) => <li key={g} className="text-xs text-orange-800 flex gap-2"><span>•</span>{g}</li>)}
                </ul>
              </div>
            )}
          </>
        )}

        {/* CTAs */}
        <div className="grid gap-3">
          <button onClick={() => handleCheckout("build")} className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl transition-colors shadow-md text-sm">{t.cta_build}</button>
                  <SignedIn>
            <a href="/dashboard" className="w-full block text-center bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-4 rounded-xl transition-colors shadow-md text-sm">View My Dashboard →</a>
          </SignedIn>
          <SignedOut>
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-center mb-1">
              <p className="text-sm text-slate-600 mb-3">💾 Sign up to save your results and download your assessment report</p>
              <SignInButton mode="modal">
                <button className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 rounded-xl text-sm">Create Free Account to Save Results</button>
              </SignInButton>
            </div>
          </SignedOut>
          <button onClick={() => handleCheckout("expert")} className="w-full bg-white hover:bg-slate-50 text-slate-700 font-semibold py-4 rounded-xl border border-slate-200 text-sm">{t.cta_expert}</button>
          <button onClick={() => { setBlockIdx(-1); setAnswers({}); setOther({}); setAiResult(null); setAiError(false) }}
            className="text-slate-400 text-sm py-2 hover:text-slate-600">{t.cta_retake}</button>
        </div>
      </div>
    )
  }

  return (
    <div id="top" className="min-h-screen bg-slate-50">
      <div className="sticky top-0 z-50 bg-white border-b border-slate-200 px-4 py-3 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center">
            <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
          </div>
          <span onClick={() => { setBlockIdx(-1); setAnswers({}); setOther({}); setAiResult(null); setAiError(false); setCvParsed(false) }} className="font-bold text-slate-800 text-sm cursor-pointer hover:text-blue-600">CaseBuilder</span>
        </div>
      
      <div className="flex items-center gap-2">
        {LANGS.map(l => <button key={l} onClick={() => setLang(l)} className={`px-2 py-1 rounded text-xs font-bold ${lang === l ? "bg-blue-600 text-white" : "text-slate-400 hover:text-slate-700"}`}>{LANG_LABELS[l]}</button>)}
        <SignedOut>
          <SignInButton mode="modal">
            <button className="text-xs font-medium text-slate-600 hover:text-blue-600 px-2 py-1">Sign In</button>
          </SignInButton>
        </SignedOut>
       <SignedIn>
          <a href="/dashboard" className="text-xs font-medium text-slate-600 hover:text-blue-600 px-2 py-1">My Cases</a>
          <UserButton />
        </SignedIn>
      </div>
      </div>

      {blockIdx === -1 && (
        <div className="max-w-lg mx-auto px-4 py-16 text-center">
          <div className="w-16 h-16 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <svg className="w-8 h-8 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
          </div>
          <h1 className="text-3xl font-bold text-slate-900 mb-4">{t.title}</h1>
          <p className="text-slate-600 mb-3 leading-relaxed">{t.subtitle}</p>
          <p className="text-slate-400 text-sm mb-10">{t.anonymous}</p>
          {cvParsing ? (
  <div className="flex items-center gap-3 justify-center mb-6">
    <div className="w-5 h-5 border-2 border-blue-200 border-t-blue-600 rounded-full animate-spin" />
    <span className="text-slate-600 text-sm">Reading your CV...</span>
  </div>
) : cvParsed ? (
  <div className="bg-green-50 border border-green-200 rounded-xl px-4 py-3 mb-6 flex items-center gap-2">
    <span className="text-green-600">✓</span>
    <span className="text-green-700 text-sm font-medium">CV analyzed — questionnaire pre-filled!</span>
  </div>
) : (
  <label className="cursor-pointer block mb-4">
    <div className="border-2 border-dashed border-slate-200 rounded-xl px-6 py-4 hover:border-blue-400 hover:bg-blue-50 transition-all text-center">
      <p className="text-slate-500 text-sm">📎 Upload CV to pre-fill answers (optional)</p>
      <p className="text-slate-400 text-xs mt-1">PDF or DOCX · Max 10MB</p>
    </div>
    <input type="file" accept=".pdf,.docx" className="hidden"
      onChange={e => { const f = e.target.files?.[0]; if (f) handleCvUpload(f) }} />
  </label>
)}
<button onClick={() => setBlockIdx(0)} className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-10 py-4 rounded-xl shadow-lg text-lg">{t.start}</button>
        </div>
      )}

      {blockIdx >= 0 && blockIdx < BLOCKS.length && (
        <div className="max-w-2xl mx-auto px-4 py-8">
          <div className="flex items-center gap-2 mb-8">
            {BLOCKS.map((b, i) => (
              <div key={b.id} className="flex items-center gap-2 flex-1">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 ${i < blockIdx ? "bg-emerald-500 text-white" : i === blockIdx ? "bg-blue-600 text-white" : "bg-slate-200 text-slate-500"}`}>{i < blockIdx ? "✓" : b.id}</div>
                {i < BLOCKS.length - 1 && <div className={`h-0.5 flex-1 ${i < blockIdx ? "bg-emerald-400" : "bg-slate-200"}`} />}
              </div>
            ))}
            <span className="text-xs text-slate-400 ml-2">{t.step(blockIdx + 1, BLOCKS.length)}</span>
          </div>
          <h2 className="text-xl font-bold text-slate-900 mb-6">{t[`block_${BLOCKS[blockIdx].id}`]}</h2>
          {curBlock.questions.map(({ key, type }) => renderQ(key, type))}
          <div className="flex gap-3 mt-8">
            {blockIdx > 0 && <button onClick={() => setBlockIdx(i => i - 1)} className="flex-1 py-3 rounded-xl border border-slate-200 text-slate-600 font-medium hover:bg-slate-50 text-sm">{t.back}</button>}
            <button onClick={goNext} disabled={!blockOk()} className="flex-1 py-3 rounded-xl bg-blue-600 text-white font-bold hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed text-sm">
              {blockIdx === BLOCKS.length - 1 ? t.analyze : t.next}
            </button>
          </div>
        </div>
      )}

      {blockIdx === BLOCKS.length && (
        <div className="max-w-lg mx-auto px-4 py-24 text-center">
          <div className="w-14 h-14 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mx-auto mb-6" />
          <p className="text-slate-600 font-medium">{t.analyzing}</p>
        </div>
      )}

      {blockIdx === BLOCKS.length + 1 && renderResult()}
   <div className="fixed bottom-6 right-6 z-50">
  {chatOpen && (
    <div className="mb-3 bg-white rounded-2xl shadow-2xl border border-slate-200 w-80 overflow-hidden">
      <div className="bg-blue-600 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 bg-green-400 rounded-full"></div>
          <span className="text-white text-sm font-semibold">Contact Us</span>
        </div>
        <button onClick={() => setChatOpen(false)} className="text-white/70 hover:text-white text-lg">×</button>
      </div>
      {chatSent ? (
        <div className="p-6 text-center">
          <div className="text-3xl mb-2">✓</div>
          <p className="text-slate-700 font-semibold text-sm">Message sent!</p>
          <p className="text-slate-400 text-xs mt-1">We&apos;ll reply within 24 hours</p>
        </div>
      ) : (
        <div className="p-4 space-y-3">
          <p className="text-xs text-slate-500">Have a question? Send us a message — we reply within 24 hours.</p>
          <input value={chatName} onChange={e => setChatName(e.target.value)}
            placeholder="Your name" className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 focus:outline-none focus:border-blue-400" />
          <input value={chatEmail} onChange={e => setChatEmail(e.target.value)}
            placeholder="Your email" type="email" className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 focus:outline-none focus:border-blue-400" />
          <textarea value={chatMsg} onChange={e => setChatMsg(e.target.value)}
            placeholder="Your question..." rows={3} className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2 resize-none focus:outline-none focus:border-blue-400" />
          <button onClick={sendChat} disabled={chatLoading || !chatName || !chatEmail || !chatMsg}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold py-2.5 rounded-lg disabled:opacity-40">
            {chatLoading ? "Sending..." : "Send Message"}
          </button>
        </div>
      )}
    </div>
  )}
  <button onClick={() => setChatOpen(o => !o)}
    className="w-14 h-14 bg-blue-600 hover:bg-blue-700 rounded-full shadow-lg flex items-center justify-center transition-all">
    {chatOpen ? (
      <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
    ) : (
      <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>
    )}
  </button>
</div>
    </div>
  )
}
